# Generated by Django 3.0.5 on 2020-04-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delegations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegations',
            name='main',
            field=models.BooleanField(default=False, verbose_name='Oficina principal'),
        ),
    ]
